chore: consolidate code signing, fix retry logic (#1825)
- Move common signing, notarization & DMG creation targets to common.mk
- Improve retry logic error handling in GitHub Workflows

Signed-off-by: Justin Kolberg <amd.prophet@gmail.com>

diff --git a/.github/workflows/workflow-build-otelcol-config-platform.yml b/.github/workflows/workflow-build-otelcol-config-platform.yml
--- a/.github/workflows/workflow-build-otelcol-config-platform.yml
+++ b/.github/workflows/workflow-build-otelcol-config-platform.yml
@@ -125,7 +125,21 @@ jobs:
         env:
           AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
         working-directory: ./pkg/tools/otelcol-config
-        run: make ${{ inputs.platform }}-sign
+        run: |
+          signed=false
+
+          for _ in $(seq 1 5); do
+            if make ${{ inputs.platform }}-sign; then
+              signed=true
+              break
+            fi
+            sleep 5
+          done
+
+          if ! $signed; then
+            echo "Failed to sign binary & dmg file"
+            exit 1
+          fi
 
       - name: Store binary as action artifact
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
